spring:
    application:
        name: contract-server
    redis:
        database: 1
        host: 127.0.0.1
        port: 6379
        timeout: 5000
        jedis:
            pool:
                max-active: 20
                max-idle: 10
                min-idle: 0
                max-wait: -1
    datasource:
        name: xj_cloud
        url: jdbc:mysql://39.108.50.114:7089/xj_cloud?useUnicode=true&characterEncoding=UTF8&useSSL=true&serverTimezone=UTC
        username: root
        password: lrstmysql
        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: test
        password: 123456
server:
    port: 18080
    undertow:
        max-http-post-size: 0
        io-threads: 4
        worker-threads: 20
        buffer-size: 1024
        direct-buffers: true
eureka:
    instance:
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
        prefer-ip-address: true
        #ip-address: localhost
        metadata-map:
            cname: 词条服务后台服务
            type: app_server
    client:
        serviceUrl:
            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
mybatis:
    basepackage: gov.xjcloud.provider.contract
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: "classpath*:mapper/*.xml"
# Mysql Database
#driver  =   com.mysql.jdbc.Driver
#url     =   jdbc:mysql://localhost:3306/testjdbc
#user    =   root
#password=   ruan